sequenceDiagram
    actor User
    participant System
    participant MapAPI
    participant AISystem
    participant FoodAPI

    User->>System: "Choose meals and text prompt about interests"
    activate System

    System->System: "Get User's location"
    System->AISystem: "What should this user eat?"
    activate AISystem

    AISystem -> FoodAPI: "Restaurants near user"
    activate FoodAPI

    FoodAPI --> AISystem: "Lists of Restaurants"
    deactivate FoodAPI

    AISystem -->System: Suggestion: food and restaurants
    deactivate AISystem

    System->MapAPI: Get map data for restaurants
    activate MapAPI
    MapAPI-->System: Return map data/image
    deactivate MapAPI

    System-->>User: Display [Map] with restaurants
    deactivate System